apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: demowebs.luxor.tech
spec:
  scope: Namespaced
  group: luxor.tech
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                image:
                  type: string
                volumeMounts:  # Define volume mounts
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mountPath:
                        type: string
                      subPath:
                        type: string
                      readOnly:
                        type: boolean
                volumes:  # Define volumes
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      configMap:
                        type: object
                        properties:
                          name:
                            type: string
  names:
    kind: DemoWeb
    plural: demowebs
    singular: demoweb
    shortNames:
      - dweb